# config/packages/liip_imagine.yaml
liip_imagine:
    filter_sets:
        obra_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 300], mode: outbound }
        obra_lowres:
            quality: 60
            filters:
                thumbnail: { size: [100, 150], mode: inset }
