security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_provider:
            entity:
                class: App\Entity\User
                property: nom_usuari

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_home

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TREBALLADOR, ROLE_CLIENT, ROLE_USER]
        ROLE_TREBALLADOR: [ROLE_USER]
        ROLE_CLIENT: [ROLE_USER]
        ROLE_ANONIM: []

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/editors, roles: PUBLIC_ACCESS }
        - { path: ^/privacitat, roles: PUBLIC_ACCESS }
        - { path: ^/cookies, roles: PUBLIC_ACCESS }
        - { path: ^/contacte, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10