security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_provider:
            entity:
                class: App\Entity\User
                property: nom_usuari

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home_back

            logout:
                path: app_logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TREBALLADOR]
        ROLE_TREBALLADOR: [ROLE_USER]
        ROLE_CLIENT: [ROLE_USER]

    access_control:
        - { path: ^/admin, roles: ROLE_TREBALLADOR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10