# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        obres:
            uri_prefix: /images/obres
            upload_destination: '%kernel.project_dir%/public/images/obres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer